### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by dkhamsing** [dkhamsing/awesome_bot#1]
- [x] publish as gem
- [x] test white list `awesome_bot ../README.md --white-list gph.is,travis-ci.org/dkhamsing`
- [x]  white list 
- [x] work on cli
- [x] change logic to be `--allow-dupe`
- [x] Rename result_uniq
- [x]  cleanup `success`, `results`
- [x] split out core so it can be reused
- [x] gemspec use product constant
- [x]  rescue if file does not exist 
- [x] dupe is busted
- [x]  example `.travis.yml`
- [x] readme
- [x]  test
- [x]  update usage
